server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kaiyuan?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 60000
      validation-timeout: 2000

